version: '3.7'

services:
  frontend:
    image: jerilcj3/lithan:frontend-latest
    #build:
    #  context: frontend
    #  dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  backend:
    image: jerilcj3/lithan:backend-latest
    #build:
    #  context: backend
    #  dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:johnjose@db:5432/cilos
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
    command: ['python', '/app/seed.py']
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=johnjose
      - POSTGRES_DB=cilos
    ports:
      - '5432:5432'
    networks:
      - mynetwork

networks:
  mynetwork:
